# Generated by Django 6.0.8 on 2026-08-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("site", "Сайт")],
                        max_length=16,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(blank=True, null=True, verbose_name="Telegram id"),
                ),
                (
                    "username",
                    models.CharField(blank=True, default="", max_length=32, verbose_name="Ник"),
                ),
                ("user_agent", models.TextField(blank=True, default="", verbose_name="Браузер")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Когда"),
                ),
            ],
            options={
                "verbose_name": "Вход",
                "verbose_name_plural": "Входы",
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
