# Generated by Django 6.0.8 on 2026-08-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Learner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Telegram id"
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        blank=True, max_length=64, null=True, unique=True, verbose_name="Хэш ключа"
                    ),
                ),
                (
                    "username",
                    models.CharField(blank=True, default="", max_length=32, verbose_name="Ник"),
                ),
                ("scheduling", models.BooleanField(default=False, verbose_name="Новая логика")),
                ("reminders_on", models.BooleanField(default=True, verbose_name="Напоминания")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Первый заход"
                    ),
                ),
            ],
            options={
                "verbose_name": "Человек",
                "verbose_name_plural": "Люди",
                "ordering": ("-created_at", "-id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("telegram_id__isnull", False),
                            ("key_hash__isnull", False),
                            _connector="OR",
                        ),
                        name="learner_has_identity",
                    )
                ],
            },
        ),
    ]
