# Generated by Django 6.0.8 on 2026-08-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_visit_learner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learner",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="visit",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Создано"),
        ),
    ]
