"""Промпты для рисования картинок к карточкам.

Словарь заодно и белый список: карточку без записи здесь команда не трогает.
Так решается «не всем нужна картинка» — списком, который видно глазами, а не
догадками по переводу.

Промпты английские: FLUX по-русски рисует плохо. Ключ словаря — перевод ровно
как в базе, вместе с пометкой в скобках: «врач (муж. род)» и «врач (жен. род)»
должны получить разные картинки.

Чего здесь нет намеренно:
  * числительных — «пять» рисуется пятью предметами, модель так не умеет;
  * служебных слов и вопросов — «из», «под», «почему» не изображаются;
  * большинства признаков — «большой», «далёкий», «правильный» без пары
    бессмысленны, а «худой» и «толстый» дают неприятную выборку;
  * абстрактных существительных — «уровень», «возраст», «речь», «гражданство».
"""

#: Приписка ко всем промптам. Без неё колода выглядит свалкой: у каждой картинки
#: свой фон и своя манера. `no text` обязателен — модель иначе лезет подписывать
#: рисунок исковерканными буквами.
STYLE = (
    "children's book illustration, soft watercolor, warm friendly colours, "
    "simple clean plain background, gentle cartoon style, no text, no letters"
)

#: Женские фигуры — в хиджабе. Приписано в сами промпты, а не в `STYLE`: в стиле
#: это относилось бы и к карточкам, где людей нет вовсе.
PROMPTS: dict[str, str] = {
    # --- Люди -----------------------------------------------------------------
    "мальчик": "one cheerful boy standing, full figure",
    "мальчики": "three cheerful boys standing together",
    "девочка": "one cheerful girl wearing a hijab, modest dress, full figure",
    "девочки": "three cheerful girls wearing hijabs and modest dresses",
    "мужчина": "one adult man standing, full figure",
    "мужчины": "three adult men standing together",
    "женщина": "one adult woman wearing a hijab and modest long dress, full figure",
    "женщины": "three adult women wearing hijabs and modest long dresses",
    "ребёнок": "one small toddler standing",
    "дети": "several small children playing together",
    "друг": "two boys as friends, arms over shoulders",
    "друзья": "a group of boys as friends together",
    "подруга": "two girls wearing hijabs as friends together",
    "подруги": "a group of girls wearing hijabs as friends together",
    # --- Профессии ------------------------------------------------------------
    "учитель": "a male teacher at a blackboard holding chalk",
    "учителя (муж. род)": "three male teachers standing in a classroom",
    "учительница": "a female teacher wearing a hijab at a blackboard holding chalk",
    "учительницы": "three female teachers wearing hijabs in a classroom",
    "преподаватель": "a male university lecturer with books at a lectern",
    "преподаватели": "three male university lecturers with books",
    "студент": "a male student with a backpack and notebook",
    "студенты": "three male students with backpacks and notebooks",
    "студентка": "a female student wearing a hijab with a backpack and notebook",
    "студентки": "three female students wearing hijabs with backpacks",
    "врач (муж. род)": "a male doctor in a white coat with a stethoscope",
    "врачи (муж. род)": "three male doctors in white coats with stethoscopes",
    "врач (жен. род)": "a female doctor wearing a hijab and white coat with a stethoscope",
    "врачи (жен. род)": "three female doctors wearing hijabs and white coats",
    "инженер": "a male engineer in a helmet with blueprints",
    "инженеры": "three male engineers in helmets with blueprints",
    "полицейский": "a police officer in uniform and cap",
    "полицейские": "three police officers in uniform",
    "должностное лицо": "an office clerk at a desk with papers and a stamp",
    "должностные лица": "three office clerks at desks with papers",
    "мусульманин": "a muslim man in a white robe and prayer cap",
    "мусульмане": "a group of muslim men in white robes and prayer caps",
    "мусульманка": "a muslim woman in a hijab and modest long dress",
    "мусульманки": "a group of muslim women in hijabs and modest long dresses",
    # --- Родня ----------------------------------------------------------------
    "семья": "a family together: father, mother in a hijab, and two children",
    "отец": "a father holding his small child",
    "отцы": "three fathers each holding a child",
    "мать": "a mother wearing a hijab holding her small child",
    "матери": "three mothers wearing hijabs each holding a child",
    "брат": "two brothers standing side by side",
    "братья": "three brothers standing together",
    "сестра": "two sisters wearing hijabs standing side by side",
    "сёстры": "three sisters wearing hijabs standing together",
    "дедушка": "an elderly grandfather with a grey beard and a cane",
    "дедушки": "three elderly grandfathers with grey beards",
    "бабушка": "an elderly grandmother wearing a hijab, kind face",
    "бабушки": "three elderly grandmothers wearing hijabs",
    "сын": "a father and his son standing together",
    "сыновья": "a father with three sons standing together",
    "дочь": "a mother in a hijab and her daughter in a hijab together",
    "дочери": "a mother in a hijab with three daughters in hijabs",
    "дядя (со стороны отца)": "an uncle with his young nephew beside him",
    "дяди (со стороны отца)": "three uncles standing together",
    "тётя (со стороны отца)": "an aunt wearing a hijab with her young niece beside her",
    "тёти (со стороны отца)": "three aunts wearing hijabs standing together",
    "дядя (со стороны матери)": "an uncle with his young nephew beside him",
    "тётя (со стороны матери)": "an aunt wearing a hijab with her young niece beside her",
    # --- Животные -------------------------------------------------------------
    "верблюд": "one camel standing on desert sand",
    "верблюды": "a herd of camels on desert sand",
    "конь": "one horse standing in a meadow",
    "кони": "a herd of horses in a meadow",
    "осёл": "one grey donkey standing",
    "ослы": "several grey donkeys standing together",
    "корова": "one cow standing in a green field",
    "коровы": "a herd of cows in a green field",
    "слон": "one grey elephant standing",
    "слоны": "a herd of grey elephants",
    "лев": "one lion with a mane sitting",
    "львы": "a pride of lions together",
    "газель": "one gazelle with slender horns standing",
    "газели": "a herd of gazelles",
    "кошка": "one cat sitting",
    "кошки": "several cats sitting together",
    "курица": "one brown hen standing",
    "куры": "several brown hens pecking the ground",
    "петух": "one rooster with a red comb crowing",
    "петухи": "several roosters with red combs",
    "голубь": "one grey pigeon perched",
    "голуби": "a flock of grey pigeons",
    "рыба": "one fish swimming underwater",
    "маленькая птичка": "one tiny sparrow perched on a twig",
    "маленькие птички": "several tiny sparrows on a branch",
    # --- Еда и питьё ----------------------------------------------------------
    "хлеб": "a loaf of bread on a wooden board",
    "мясо": "raw red meat on a wooden board",
    "молоко": "a tall glass of milk",
    "вода": "a clear glass of water",
    "яйцо": "one white chicken egg",
    "яйца": "several white chicken eggs in a bowl",
    "яблоко": "one red apple",
    "яблоки": "a pile of red apples",
    "апельсин": "one orange fruit",
    "апельсины": "a pile of orange fruits",
    "еда": "a plate of warm food on a table",
    # --- Дом и вещи -----------------------------------------------------------
    "дом": "one small house with a door and windows, seen from outside",
    "дома": "a row of small houses along a street",
    "комната": "a tidy room with a bed and a window, seen from inside",
    "дверь": "one closed wooden door in a wall",
    "двери": "several wooden doors in a row",
    "стол": "one wooden table, nothing on it",
    "столы": "several wooden tables in a row",
    "стул": "one wooden chair",
    "стулья": "several wooden chairs in a row",
    "кровать": "one neatly made bed in a bedroom",
    "кровати": "several beds in a row in a room",
    "холодильник": "one closed white refrigerator in a kitchen",
    "холодильники": "several white refrigerators in a row",
    "тарелка": "one empty ceramic plate",
    "тарелки": "a stack of ceramic plates",
    "стакан": "one empty drinking glass",
    "стаканы": "several drinking glasses in a row",
    "ложка": "one metal spoon",
    "ложки": "several metal spoons together",
    "телевизор": "one television set on a stand",
    "телевизоры": "several television sets in a row",
    "телефон": "one telephone handset",
    "телефоны": "several telephones in a row",
    "ключ": "one metal door key",
    "ключи": "a bunch of metal door keys",
    "конверт": "one sealed paper envelope",
    "конверты": "several paper envelopes stacked",
    "забор": "a wooden fence along a garden",
    "заборы": "several wooden fences",
    "обувь": "one pair of shoes side by side",
    "рубашка": "one folded shirt",
    "рубашки": "several folded shirts stacked",
    "пальто": "one long winter overcoat on a hanger",
    "одежда": "clothes hanging on a rack",
    "меч": "one straight sword with a hilt",
    "мяч": "one round ball",
    "фотография": "one printed photograph with a white border",
    # --- Учёба ----------------------------------------------------------------
    "книга": "one open book with blank pages",
    "книги": "a stack of closed books",
    "тетрадь": "one school exercise notebook",
    "тетради": "a stack of school exercise notebooks",
    "ручка": "one ballpoint pen",
    "ручки": "several ballpoint pens together",
    "парта": "one school desk with a chair",
    "парты": "rows of school desks in a classroom",
    "классная доска": "one green classroom blackboard, blank",
    "классные доски": "several classroom blackboards, blank",
    "школа": "one school building with a yard, seen from outside",
    "школы": "several school buildings",
    "газета": "one folded newspaper",
    "газеты": "a stack of folded newspapers",
    "рукописный экземпляр Корана": "an open handwritten quran on a wooden book stand",
    "рукописные экземпляры Корана": "several handwritten qurans stacked on a shelf",
    # --- Места и природа ------------------------------------------------------
    "мечеть": "one mosque with a dome and a minaret, seen from outside",
    "мечети": "several mosques with domes and minarets",
    "город": "a city of houses and towers seen from a distance",
    "дерево": "one leafy tree",
    "деревья": "a group of leafy trees",
    "роза": "one red rose flower",
    "розы": "a bouquet of red roses",
    "солнце": "the bright sun in a clear blue sky",
    "луна": "the moon in a dark night sky with stars",
    "чемодан": "one closed travel suitcase with a handle",
    "чемоданы": "several travel suitcases together",
    "автомобиль": "one car seen from the side",
    "автомобили": "several cars parked in a row",
    "корабль": "one ship sailing on the sea",
    "корабли": "several ships sailing on the sea",
    "самолёт": "one airplane flying in the sky",
    "самолёты": "several airplanes flying in the sky",
    # --- Страны ---------------------------------------------------------------
    "Пакистан": "the flag of Pakistan on a flagpole",
    "Турция": "the flag of Turkey on a flagpole",
    "Египет": "the flag of Egypt on a flagpole",
    "Сирия": "the flag of Syria on a flagpole",
    # --- Действия -------------------------------------------------------------
    "кушает": "a boy eating a meal at a table",
    "читает": "a boy reading an open book",
    "пьёт": "a boy drinking water from a glass",
    "пишет": "a boy writing in a notebook with a pen",
    "молится": "a muslim man praying on a prayer rug",
    "бежит": "a boy running fast",
    "совершает малое омовение": "a man washing his hands and arms at a tap for ablution",
    "сидит": "a boy sitting on a chair",
    "открывает": "a hand opening a wooden door",
    "закрывает": "a hand closing a wooden door",
    "смеётся": "a boy laughing happily",
    "играет": "a boy playing with a ball",
    "ходит, идёт": "a boy walking along a path",
    "нюхает": "a boy smelling a flower",
    "готовит (о еде)": "a woman wearing a hijab cooking at a stove",
    "спит": "a boy sleeping in a bed",
    "садится верхом, едет (на чём-либо)": "a boy riding on a horse",
    "работает": "a man working at a desk",
    "отправляется в путешествие": "a traveller with a suitcase at an airport",
    # --- Состояния ------------------------------------------------------------
    "счастливый": "a boy with a wide happy smile",
    "печальный": "a boy with a sad downcast face",
    "больной": "a boy lying sick in bed with a thermometer",
    "женатый": "a groom and a bride in a hijab standing together",
}
