# Generated by Django 6.0.8 on 2026-08-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("arabic", models.TextField(help_text="С огласовками", verbose_name="Арабское")),
                ("translation_ru", models.TextField(verbose_name="Перевод")),
                (
                    "transliteration",
                    models.TextField(blank=True, default="", verbose_name="Транслитерация"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="entries/", verbose_name="Картинка"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Добавлено"
                    ),
                ),
            ],
            options={
                "verbose_name": "Слово",
                "verbose_name_plural": "Слова",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("arabic", "translation_ru"), name="uq_entry_arabic_translation"
                    )
                ],
            },
        ),
    ]
