# Generated by Django 6.0.8 on 2026-08-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("word", "Слово"), ("phrase", "Фраза")],
                        max_length=8,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "arabic",
                    models.TextField(
                        help_text="С огласовками, как распознано", verbose_name="Арабское"
                    ),
                ),
                (
                    "arabic_norm",
                    models.TextField(
                        db_index=True, editable=False, verbose_name="Ключ поиска похожих"
                    ),
                ),
                ("translation_ru", models.TextField(verbose_name="Перевод")),
                (
                    "transliteration",
                    models.TextField(blank=True, default="", verbose_name="Транслитерация"),
                ),
                (
                    "topic",
                    models.TextField(blank=True, db_index=True, default="", verbose_name="Тема"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("textbook", "Учебник"),
                            ("manual", "Вручную"),
                            ("ai_generated", "Сгенерировано ИИ"),
                        ],
                        max_length=16,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Добавлено"
                    ),
                ),
            ],
            options={
                "verbose_name": "Единица",
                "verbose_name_plural": "Единицы",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("arabic", "translation_ru"), name="uq_entry_arabic_translation"
                    )
                ],
            },
        ),
    ]
