# Generated by Django 6.0.8 on 2026-08-06 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={"verbose_name": "Слово", "verbose_name_plural": "Слова"},
        ),
    ]
