# Generated by Django 6.0.8 on 2026-08-06 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0002_alter_entry_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="kind",
        ),
    ]
