# Generated by Django 6.0.8 on 2026-08-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0002_entry_themes"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="is_word",
            field=models.BooleanField(
                default=False,
                help_text="Снятая галочка означает фразу: карточка не попадёт в прогон по словам",
                verbose_name="Отдельное слово",
            ),
        ),
    ]
