# Generated by Django 6.0.8 on 2026-08-10 15:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0003_entry_is_word"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="themes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("numbers", "Цифры"),
                        ("family", "Семья"),
                        ("greetings", "Знакомство"),
                        ("verbs", "Глаголы"),
                        ("antonyms", "Антонимы"),
                        ("nouns", "Существительные"),
                        ("questions", "Вопросы и предлоги"),
                        ("dialog3", "Третий диалог"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=list,
                verbose_name="Темы",
            ),
        ),
    ]
