# Generated by Django 6.0.8 on 2026-08-14 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0006_move_entries"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="entry",
            name="uq_entry_arabic_translation",
        ),
        migrations.DeleteModel(
            name="Entry",
        ),
    ]
