# Generated by Django 6.0.8 on 2026-08-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0010_alter_phrase_themes_alter_word_themes"),
    ]

    operations = [
        migrations.AddField(
            model_name="phrase",
            name="image_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="phrase",
            name="image_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="wordform",
            name="image_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="wordform",
            name="image_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="image",
            field=models.ImageField(
                blank=True,
                height_field="image_height",
                null=True,
                upload_to="cards/",
                verbose_name="Картинка",
                width_field="image_width",
            ),
        ),
        migrations.AlterField(
            model_name="wordform",
            name="image",
            field=models.ImageField(
                blank=True,
                height_field="image_height",
                null=True,
                upload_to="cards/",
                verbose_name="Картинка",
                width_field="image_width",
            ),
        ),
    ]
