# Generated by Django 6.0.8 on 2026-08-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0011_phrase_image_height_phrase_image_width_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phrase",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="word",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Создано"),
        ),
    ]
