# Generated by Django 6.0.8 on 2026-08-17 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0004_created_at_label"),
        ("vocabulary", "0012_created_at_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Создано"),
                ),
                ("level", models.PositiveSmallIntegerField(default=0, verbose_name="Уровень")),
                ("step", models.PositiveSmallIntegerField(default=0, verbose_name="Верных подряд")),
                ("due_at", models.DateTimeField(db_index=True, verbose_name="Показать")),
                (
                    "answered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Оценили"),
                ),
                (
                    "reminded_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Отправляли в чат"),
                ),
                (
                    "form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="vocabulary.wordform",
                        verbose_name="Форма",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="common.learner",
                        verbose_name="Человек",
                    ),
                ),
                (
                    "phrase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="vocabulary.phrase",
                        verbose_name="Фраза",
                    ),
                ),
            ],
            options={
                "verbose_name": "Состояние карточки",
                "verbose_name_plural": "Состояния карточек",
                "ordering": ("-created_at", "-id"),
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("form__isnull", False), ("phrase__isnull", True)),
                            models.Q(("form__isnull", True), ("phrase__isnull", False)),
                            _connector="OR",
                        ),
                        name="cardstate_one_card",
                    ),
                    models.UniqueConstraint(
                        fields=("learner", "form"), name="uq_cardstate_learner_form"
                    ),
                    models.UniqueConstraint(
                        fields=("learner", "phrase"), name="uq_cardstate_learner_phrase"
                    ),
                ],
            },
        ),
    ]
