# Generated by Django 6.0.8 on 2026-08-17 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0001_initial"),
        ("vocabulary", "0012_created_at_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Создано"),
                ),
                ("sent_at", models.DateTimeField(db_index=True, verbose_name="Отправлено")),
                (
                    "form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_posts",
                        to="vocabulary.wordform",
                        verbose_name="Форма",
                    ),
                ),
                (
                    "phrase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_posts",
                        to="vocabulary.phrase",
                        verbose_name="Фраза",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слово в группе",
                "verbose_name_plural": "Слова в группе",
                "ordering": ("-created_at", "-id"),
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("form__isnull", False), ("phrase__isnull", True)),
                            models.Q(("form__isnull", True), ("phrase__isnull", False)),
                            _connector="OR",
                        ),
                        name="grouppost_one_card",
                    ),
                    models.UniqueConstraint(fields=("form",), name="uq_grouppost_form"),
                    models.UniqueConstraint(fields=("phrase",), name="uq_grouppost_phrase"),
                ],
            },
        ),
    ]
