# Generated by Django 6.0.8 on 2026-08-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0002_grouppost"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardstate",
            name="lapsed_from",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Упала с уровня"),
        ),
        migrations.AddField(
            model_name="cardstate",
            name="lapses",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Промахов за жизнь"),
        ),
    ]
