"""Промпты для фраз и предложений колоды.

Фраза — это сцена, а не предмет, поэтому промпт описывает, что происходит.
Вопросительные предложения рисуются той же сценой плюс вопросительный жест:
самого вопроса картинкой не передать, а действие в нём — можно.

Разные по грамматике карточки нередко получают одну и ту же сцену: «я ем хлеб»
и «ты ешь хлеб» картинкой не различить, лицо отрабатывается арабским текстом.
Дублирование здесь намеренное.

Чего здесь нет намеренно:
  * счётных фраз — «три книги», «пять мальчиков»: модель ошибается в счёте,
    а неверное количество на карточке учит вранью;
  * порядковых — «первый урок», «второй раздел»: без цифры их не показать,
    а цифра запрещена стилем (`no text`);
  * всего, что требует надписи, — «как называется этот город?», «имя мальчика»;
  * абстрактных — «какой твой язык?», «уровень студентов», «возраст мальчика».
"""

#: Женская фигура задумана: только сюда приписывается MODESTY.
WITH_WOMEN: dict[str, str] = {
    "как тебя зовут? (к женщине)": "two women in conversation, one asking with an open gesture",
    "как твои дела? (к женщине)": "two women greeting each other warmly, asking after each other",
    "откуда ты? (к женщине)": "two women beside a world map, one pointing at it questioningly",
    "ты египтянка?": "two women beside the flag of Egypt, one asking questioningly",
    "я сирийка": "a woman standing proudly beside the flag of Syria",
    "а какое у тебя гражданство? (к женщине)": "two women talking, one holding an open passport",
    "кто ты? (к женщине)": "two women facing each other, one asking with a questioning gesture",
    "как зовут твою сестру?": "three girls in a row, two of them talking, questioning gesture",
    "это моя сестра": "two girls standing side by side",
    "это моя подруга": "two girls standing together as close friends",
    "это моя мать": "one adult woman and one girl standing side by side",
    "это моя бабушка": "one elderly woman and one girl standing side by side",
    "это моя дочь": "one adult woman and one small girl standing side by side",
    "это моя тётя (со стороны отца)": "one adult woman and one girl standing side by side",
    "это моя тётя (со стороны матери)": "one adult woman and one girl standing side by side",
    "она моя подруга": "two girls standing side by side",
    "ты моя сестра": "two girls standing side by side",
    "дочь моего дяди по матери — учительница": "one adult woman at a blackboard and one girl",
    "она врач": "a female doctor in a white coat with a stethoscope",
    "она студентка": "a female student with a backpack and notebook",
    "она учительница": "a female teacher standing at a blackboard",
    "она инженер": "a female engineer in a helmet holding blueprints",
    "она учительница?": "two women talking, one at a blackboard, questioning gesture",
    "я учительница": "a female teacher standing at a blackboard with chalk",
    "ты учительница": "a female teacher standing at a blackboard with chalk",
    "мы студентки": "four young women with backpacks",
    "ты мусульманка": "a muslim woman in modest long clothing",
    "моя мать учительница": "one adult woman at a blackboard and one girl beside her",
    "моя сестра студентка": "two young women side by side, one with a backpack",
    "моя подруга врач": "two women side by side, one in a white doctor's coat",
    "она турецкая учительница": "a female teacher at a blackboard beside the flag of Turkey",
    "она мусульманка из Египта": "a muslim woman beside the flag of Egypt",
    "а кто это? (о женщине)": "a hand pointing at a woman with a questioning gesture",
    "эта студентка активная": "a lively female student eagerly raising her hand",
    "она активная студентка": "a lively female student eagerly raising her hand",
    "ты активная студентка": "a lively female student eagerly raising her hand",
    "студентки активные": "three young women eagerly raising their hands",
    "ты активная": "a girl running and jumping energetically",
    "эта девочка низкая": "one short small girl standing beside a tall door",
    "эта женщина печальная": "a woman with a sad downcast face",
    "она печальная": "a girl with a sad downcast face",
    "она больна": "a girl lying sick in bed with a thermometer",
    "я женат": "one man showing a ring on his finger, one woman beside him",
    "наша учительница хорошая": "a warm smiling female teacher at a blackboard",
    "ты студентка?": "two women talking, one with a backpack, questioning gesture",
    "да, я студентка": "a female student with a backpack nodding yes",
    "отец счастлив, а мать печальна": "one smiling adult man beside one sad adult woman",
    "мальчик толстый, а девочка худая": "one plump round boy beside one thin slender girl",
    "чемодан студентки": "a female student holding her suitcase",
    "тетрадь студентки": "a female student holding her notebook",
    "обувь девочки": "a girl holding her pair of shoes",
    "одежда женщины": "a woman beside her clothes on a rack",
    "школа для девочек": "three girls walking into a school building",
    "твой дом далеко (к женщине)": "a woman pointing at a house far away on the horizon",
    "её дом старый": "a girl in front of an old weathered house",
    "твой дом далеко? (к женщине)": "two women pointing at a distant house, questioning gesture",
    "это твой автомобиль? (к женщине)": "two women beside a car, one asking with a gesture",
    "да, это мой автомобиль": "a woman nodding yes beside her car",
    "девочка ест яблоко": "a girl eating a red apple",
    "ты ешь яблоко": "a girl eating a red apple",
    "что ты ешь? (к женщине)": "two women at a table, one eating, questioning gesture",
    "девочка пьёт воду": "a girl drinking water from a glass",
    "ты пьёшь молоко": "a girl drinking milk from a glass",
    "студентка читает книгу": "a female student reading an open book",
    "она читает книгу": "a woman reading an open book",
    "ты читаешь книгу": "a girl reading an open book",
    "что ты читаешь? (к женщине)": "two women, one reading a book, questioning gesture",
    "учительница пишет на доске": "a female teacher writing on a blackboard with chalk",
    "ты пишешь в тетради": "a girl writing in an exercise notebook",
    "она пишет в тетради": "a woman writing in an exercise notebook",
    "ты молишься дома": "a woman praying on a rug at home",
    "мама готовит еду": "one adult woman cooking food at a stove",
    "мать готовит мясо": "one adult woman cooking meat at a stove",
    "она готовит мясо": "a woman cooking meat at a stove",
    "я готовлю еду": "a woman cooking food at a stove",
    "ты готовишь еду": "a woman cooking food at a stove",
    "мы готовим еду": "two adult women cooking food together at a stove",
    "что готовит мама?": "one woman cooking at a stove, a questioning gesture beside",
    "девочка бежит перед домом": "a girl running in front of a house",
    "девочка смеётся": "a girl laughing brightly",
    "ты смеёшься": "a girl laughing brightly",
    "почему ты смеёшься? (к женщине)": "two women, one laughing, questioning gesture",
    "девочка играет мячом": "a girl playing with a ball",
    "ты играешь мячом": "a girl playing with a ball",
    "девочка любит розу": "a girl holding a red rose fondly",
    "ты любишь розу": "a girl holding a red rose fondly",
    "ты спишь в комнате": "a girl sleeping in a bed in a room",
    "учительница закрывает книгу": "a female teacher closing a book",
    "ты закрываешь холодильник": "a woman closing a refrigerator door",
    "девочка открывает дверь": "a girl opening a wooden door",
    "ты открываешь дверь": "a girl opening a wooden door",
    "студентка выходит из комнаты": "a female student stepping out of a room through a door",
    "бабушка сидит на стуле": "one elderly woman sitting on a wooden chair",
    "она сидит со своей сестрой": "two girls sitting side by side on a bench",
    "студентка понимает урок": "a female student at a desk with a glowing lightbulb overhead",
    "она понимает урок": "a female pupil at a desk with a glowing lightbulb overhead",
    "ты понимаешь урок? (к женщине)": "two women at a desk, one asking with a questioning gesture",
    "сестра смотрит телевизор": "a girl watching a television screen",
    "ты смотришь телевизор": "a girl watching a television screen",
    "она смотрит телевизор": "a woman watching a television screen",
    "девочка идёт в школу": "a girl walking towards a school building",
    "ты идёшь в школу": "a girl walking towards a school building",
    "ты идёшь пешком в школу": "a girl walking on foot towards a school",
    "она идёт на работу": "a woman walking towards an office with a bag",
    "она идёт с нами": "three adult women walking together",
    "куда идёт девочка?": "a girl walking away, a questioning gesture beside her",
    "ты возвращаешься из школы": "a girl coming home from school through a garden gate",
    "когда ты возвращаешься из школы? (к женщине)": "two women, one coming home, a clock behind",
    "ты живёшь в далёком городе": "a woman before a house, a distant city on the horizon",
    "она живёт в городе": "a woman in front of a house among city buildings",
    "где ты живёшь? (к женщине)": "two women before a house, one asking with a gesture",
    "врач-женщина работает в городе": "a female doctor at work among city buildings",
    "она работает в школе": "a woman working at a desk inside a school",
    "где ты работаешь? (к женщине)": "two women, one at a work desk, questioning gesture",
    "ты едешь в Сирию": "a woman with a suitcase before the flag of Syria",
    "куда ты едешь? (к женщине)": "two women, one with a suitcase, questioning gesture",
    "она любит своего сына": "one adult woman embracing one small boy",
    "ты любишь этот город? (к женщине)": "two women before a city, one asking with a gesture",
    "я с тобой (к женщине)": "two women standing side by side, shoulder to shoulder",
    "она с нами": "one adult woman standing between two other adult women",
    "мы с ней": "one adult woman standing between two other adult women",
    "она со своей матерью": "two adult women standing side by side",
    "ты со своей подругой (к женщине)": "two women standing together as friends",
    "девочки в комнате": "three girls standing in a room",
    "мусульманки дома": "three adult women indoors at home",
    "она в комнате": "a girl standing in a room",
    "моя бабушка дома": "one elderly woman sitting indoors at home",
    "где твоя мать?": "a girl looking around for someone, questioning gesture",
    "моя семья в порядке": "one adult man, one adult woman, one boy and one girl, all smiling",
    "мы одна семья": "one adult man, one adult woman, one boy and one girl standing close",
    "моя семья большая": "two adult men, two adult women, three boys and three girls together",
    "наша семья большая": "two adult men, two adult women, three boys and three girls together",
    "моя семья маленькая": "one adult man, one adult woman and one boy standing together",
    "мы едим мясо": "one adult man, one adult woman and two children eating at a table",
    "мы пьём молоко": "one adult man, one adult woman and two children drinking milk",
    "дети играют мячом": "three small children playing with a ball: two boys and one girl",
    "мы смотрим телевизор": "one adult man, one adult woman and two children before a television",
    "семья живёт в большом доме": "one man, one woman, one boy and one girl by a large house",
    "я люблю свою семью": "one adult man embracing one adult woman and two children",
    "он любит свою семью": "one adult man embracing one adult woman and two children",
    # --- Третий диалог ---------------------------------------------------------
    "девочка молится в молельной комнате": (
        "one muslim girl wearing a hijab, kneeling on a prayer rug in a small prayer room"
    ),
}

#: Предметы, животные и картинки, где люди только мужского пола.
REST: dict[str, str] = {
    "как тебя зовут? (к мужчине)": "two men in conversation, one asking with an open gesture",
    "как твои дела? (к мужчине)": "two men shaking hands warmly, asking after each other",
    "а как твои дела? (к мужчине)": "two men smiling, one returning the question with a gesture",
    "откуда ты? (к мужчине)": "two men beside a world map, one pointing at it questioningly",
    "я из Пакистана": "a man with a hand on his chest before the flag of Pakistan",
    "я из Турции": "a man with a hand on his chest before the flag of Turkey",
    "я из Египта": "a man with a hand on his chest before the flag of Egypt",
    "я из Сирии": "a man with a hand on his chest before the flag of Syria",
    "ты пакистанец?": "two men beside the flag of Pakistan, one asking questioningly",
    "да, я пакистанец": "a man nodding yes before the flag of Pakistan",
    "я турок": "a man standing proudly beside the flag of Turkey",
    "а какое у тебя гражданство? (к мужчине)": "two men talking, one holding an open passport",
    "добро пожаловать": "a man opening his arms wide in welcome at an open door",
    "добро пожаловать тебе (к мужчине)": "a man welcoming a guest with both arms open at a door",
    "до свидания": "a man waving goodbye in a doorway",
    "кто ты? (к мужчине)": "two men facing each other, one asking with a questioning gesture",
    "я друг твоего брата": "three young men standing together in a row",
    "как зовут твоего брата?": "three boys in a row, two of them talking, questioning gesture",
    "как зовут твоего сына? (к мужчине)": "two adult men talking, one small boy beside them",
    "как дела у твоей семьи? (к мужчине)": "two adult men talking, a group of people behind",
    "у меня всё хорошо": "a cheerful man giving a thumbs up",
    "это мой брат": "two boys side by side, one arm over the other's shoulder",
    "это мой друг": "two boys standing together as close friends",
    "это мой отец": "one adult man and one boy standing side by side",
    "это мой дедушка": "one elderly man with a grey beard and one boy side by side",
    "это мой сын": "one adult man and one small boy standing side by side",
    "это мой дядя (со стороны отца)": "one adult man and one boy standing side by side",
    "это мой дядя (со стороны матери)": "one adult man and one boy standing side by side",
    "он мой друг": "two boys standing side by side",
    "ты мой брат": "two boys standing side by side",
    "мы друзья": "four boys standing together in a group",
    "сын моего дяди — студент": "two young men side by side, one with a backpack",
    "мой дедушка пожилой мужчина": "one elderly man with a grey beard leaning on a cane",
    "он преподаватель": "a male university lecturer standing with books",
    "он инженер": "a male engineer in a helmet holding blueprints",
    "он студент": "a male student with a backpack and notebook",
    "он полицейский": "one adult male police officer in uniform and cap",
    "он врач?": "two men talking, one in a white doctor's coat, questioning gesture",
    "я инженер": "one adult male engineer in a helmet holding blueprints",
    "я учитель": "a male teacher standing at a blackboard with chalk",
    "ты учитель": "a male teacher standing at a blackboard with chalk",
    "мы студенты": "four young men with backpacks",
    "мы мусульмане": "four adult men in white robes and prayer caps",
    "я мусульманин": "a muslim man in a white robe and prayer cap",
    "мой отец врач": "one adult man in a white doctor's coat and one boy beside him",
    "мой брат студент": "two young men side by side, one with a backpack",
    "мой друг инженер": "two men side by side, one in a helmet holding blueprints",
    "наш друг инженер": "three men in a row, one in a helmet holding blueprints",
    "он египетский врач": "a male doctor in a white coat beside the flag of Egypt",
    "он мусульманин из Турции": "a muslim man beside the flag of Turkey",
    "он пакистанец из далёкого города": "a man before the flag of Pakistan, a distant city behind",
    "он служащий в городе": "an office clerk at a desk, city buildings behind the window",
    "он хороший преподаватель": "one warm smiling adult man with books, young men listening",
    "кто это? (о мужчине)": "a hand pointing at a man with a questioning gesture",
    "это фотография моей семьи": "a hand holding a framed photograph of four people",
    "это фотография моего отца": "a hand holding a framed photograph of one adult man",
    "этот студент активный": "a lively male student eagerly raising his hand",
    "активный студент": "a lively male student eagerly raising his hand",
    "студенты активные": "three young men eagerly raising their hands",
    "этот мальчик ленивый": "a boy sprawled lazily on a sofa, yawning",
    "ты ленивый": "a boy sprawled lazily on a sofa, yawning",
    "я активный": "a boy running and jumping energetically",
    "этот мужчина высокий": "one very tall man standing beside a low doorway",
    "высокий мужчина": "one very tall man standing beside a low doorway",
    "этот мужчина худой": "one very thin lanky man standing",
    "этот мальчик толстый": "one plump round-cheeked boy standing",
    "маленький мальчик": "one small little boy standing",
    "этот ребёнок счастливый": "a small child laughing with a wide happy smile",
    "он счастливый": "a boy with a wide happy smile",
    "этот мальчик болен": "a boy lying in bed with a thermometer, looking unwell",
    "больной ребёнок": "a small child lying in bed with a thermometer",
    "он болен": "a boy lying sick in bed with a thermometer",
    "этот ребёнок здоров": "a cheerful healthy child running with rosy cheeks",
    "мы здоровы": "three cheerful children running with rosy cheeks",
    "ты женат?": "two men talking, one showing a wedding ring on his finger",
    "я холост": "one lone young man standing by himself",
    "ты хороший врач": "a warm smiling doctor in a white coat with a stethoscope",
    "хороший учитель": "a warm smiling male teacher at a blackboard",
    "наш учитель активный": "a lively male teacher gesturing energetically at a blackboard",
    "я здесь": "a boy pointing down at the ground right at his feet",
    "ты там": "a boy pointing far away towards the horizon",
    "мы здесь": "three boys pointing down at the ground at their feet",
    "ты студент?": "two men talking, one with a backpack, questioning gesture",
    "да, я студент": "a male student with a backpack nodding yes",
    "этот урок лёгкий": "one boy at a desk smiling easily over an open notebook",
    "этот урок тяжёлый": "one boy at a desk frowning over an open notebook",
    "студент активный, а мальчик ленивый": "an eager student raising his hand beside a yawning boy",
    "мужчина женат, а студент холост": "a man with a wedding ring beside a lone young student",
    "преподаватель здоров, а студент болен": "a healthy lecturer beside a sick student in bed",
    "ребёнок болен, а врач здесь": "one boy sick in bed, one man in a white coat beside him",
    "книга студента": "a male student holding his own book",
    "ручка учителя": "a male teacher holding his pen",
    "автомобиль врача": "a doctor in a white coat standing beside his car",
    "дом инженера": "an engineer in a helmet in front of his house",
    "меч мужчины": "a man holding a straight sword",
    "рубашка брата": "a young man holding his shirt",
    "пальто дедушки": "one elderly man wearing a long winter overcoat",
    "кровать ребёнка": "a small child beside his own little bed",
    "еда ребёнка": "a small child with a plate of food",
    "мяч мальчиков": "a group of boys with their ball",
    "учитель языка": "a male teacher at a blackboard covered in decorative ornament",
    "детский врач": "one adult man in a white doctor's coat examining one small boy",
    "работа должностного лица": "an office clerk at a desk covered with papers",
    "дверь за учителем": "a male teacher standing with a closed door behind him",
    "доска перед студентами": "a blackboard in front of rows of seated young men",
    "мой дом большой": "a boy standing proudly in front of his large house",
    "твой дом близко (к мужчине)": "a man pointing at a house right across the street",
    "его дом новый": "a boy in front of a brand new freshly painted house",
    "наш дом маленький": "one man, one woman and one boy before one tiny house",
    "твой дом близко? (к мужчине)": "two men pointing at a nearby house, questioning gesture",
    "это твой дом? (к мужчине)": "two men in front of a house, one asking with a gesture",
    "да, это мой дом": "a man nodding yes in front of his house",
    "кто твой учитель? (к мужчине)": "two men talking, a teacher at a blackboard behind them",
    "моя работа лёгкая": "a man working easily at a desk with a relaxed smile",
    "твоя работа тяжёлая (к мужчине)": "a man straining over heavy work at a desk",
    "моя школа большая": "a pupil in front of one large school building",
    "наша школа близко": "pupils pointing at a school building right across the street",
    "мальчик ест хлеб": "a boy eating a slice of bread",
    "ребёнок ест яблоко": "a small child eating a red apple",
    "мужчина ест мясо": "a man eating meat from a plate",
    "я ем хлеб": "a boy eating a slice of bread",
    "ты ешь хлеб": "a boy eating a slice of bread",
    "что ест мальчик?": "a boy eating at a table, a questioning gesture beside him",
    "что ты ешь? (к мужчине)": "two men at a table, one eating, questioning gesture",
    "ты любишь еду": "a boy delightedly looking at a plate of warm food",
    "ребёнок пьёт молоко": "a small child drinking milk from a glass",
    "студент пьёт воду": "a male student drinking water from a glass",
    "я пью воду": "a boy drinking water from a glass",
    "ты пьёшь воду": "a boy drinking water from a glass",
    "что пьёт ребёнок?": "a child drinking from a glass, questioning gesture beside",
    "студент читает книгу": "a male student reading an open book",
    "мужчина читает газету": "a man reading a folded newspaper",
    "мусульманин читает Коран": "a muslim man reading an open quran on a book stand",
    "он читает газету": "a man reading a folded newspaper",
    "я читаю книгу": "a boy reading an open book",
    "ты читаешь Коран": "a muslim man reading an open quran on a book stand",
    "мы читаем газету": "two adult men reading one newspaper together",
    "что читает студент?": "a male student reading, a questioning gesture beside him",
    "что ты читаешь? (к мужчине)": "two men, one reading a book, questioning gesture",
    "кто читает газету?": "a man reading a newspaper, a questioning gesture beside him",
    "учитель пишет на доске": "a male teacher writing on a blackboard with chalk",
    "студент пишет урок в тетради": "a male student writing in an exercise notebook",
    "я пишу урок": "a boy writing a lesson in a notebook",
    "ты пишешь урок": "a boy writing a lesson in a notebook",
    "мы пишем в тетради": "two boys writing in their notebooks",
    "он пишет урок": "a man writing a lesson in a notebook",
    "что пишет учитель?": "a male teacher writing on a blackboard, questioning gesture",
    "мужчина молится в мечети": "a man praying on a rug inside a mosque",
    "я молюсь в мечети": "a man praying on a rug inside a mosque",
    "мы молимся в мечети": "three adult men praying in a row on rugs inside a mosque",
    "ты молишься в мечети": "a man praying on a rug inside a mosque",
    "ты молишься в мечети? (к мужчине)": "two men by a mosque, one praying, questioning gesture",
    "где молится мужчина?": "a man praying on a rug, a questioning gesture beside him",
    "кто молится в мечети?": "a man praying inside a mosque, questioning gesture beside",
    "мы молимся с ним": "three adult men praying in a row on rugs",
    "мужчина совершает омовение в мечети": "a man washing his arms at a tap in a mosque courtyard",
    "я совершаю омовение дома": "a man washing his arms at a tap at home",
    "мы совершаем омовение в мечети": "two adult men washing their arms at taps in a courtyard",
    "мужчина готовит мясо": "a man cooking meat at a stove",
    "мальчик бежит перед домом": "a boy running in front of a house",
    "я бегу перед домом": "a boy running in front of a house",
    "мы бежим в школе": "three boys running along a school corridor",
    "почему мальчик бежит?": "a boy running, a questioning gesture beside him",
    "ребёнок смеётся": "a small child laughing brightly",
    "я смеюсь": "a boy laughing brightly",
    "мы смеёмся": "three boys laughing together",
    "почему ребёнок смеётся?": "a laughing child with a questioning gesture beside",
    "почему ты смеёшься? (к мужчине)": "two men, one laughing, questioning gesture",
    "мальчик играет мячом": "a boy playing with a ball",
    "я играю мячом": "a boy playing with a ball",
    "мы играем мячом": "three boys playing together with a ball",
    "мальчик нюхает розу": "a boy smelling a red rose",
    "я нюхаю розу": "a boy smelling a red rose",
    "ребёнок спит на кровати": "a small child sleeping in a bed",
    "он спит на кровати": "a man sleeping in a bed",
    "я сплю в комнате": "a boy sleeping in a bed in a room",
    "мы спим в комнате": "two boys sleeping in two beds in one room",
    "ребёнок спит?": "a sleeping child with a questioning gesture beside",
    "ты много спишь": "a boy sleeping deeply with a clock showing late hours",
    "мальчик садится на коня": "a boy mounting a horse",
    "мужчина едет на верблюде": "a man riding a camel",
    "я еду на автомобиле": "a man driving a car",
    "он едет на автомобиле": "a man driving a car",
    "мы летим на самолёте": "four people seated inside an airplane cabin",
    "студент закрывает книгу": "a male student closing a book",
    "мужчина закрывает холодильник": "a man closing a refrigerator door",
    "я закрываю книгу": "a boy closing a book",
    "мы закрываем дверь": "two boys closing a wooden door together",
    "учитель открывает дверь": "a male teacher opening a wooden door",
    "я открываю дверь": "a boy opening a wooden door",
    "мы открываем книги": "three boys opening books at their desks",
    "кто открывает дверь?": "a hand opening a door, a questioning gesture beside",
    "студент выходит из комнаты": "a male student stepping out of a room through a door",
    "мужчина выходит из дома": "a man stepping out of a house through the front door",
    "я выхожу из дома": "a boy stepping out of a house through the front door",
    "ты выходишь из дома": "a boy stepping out of a house through the front door",
    "мы выходим из школы": "three boys stepping out of a school building",
    "учитель заходит в комнату": "a male teacher stepping into a room through a door",
    "ребёнок заходит в дом": "a small child stepping into a house through the door",
    "я захожу в комнату": "a boy stepping into a room through a door",
    "мы заходим в мечеть": "three adult men stepping into a mosque",
    "студент садится на стул": "a male student sitting down on a chair",
    "дедушка сидит перед телевизором": "one elderly man sitting before a television set",
    "я сажусь на стул": "a boy sitting down on a chair",
    "ты сидишь на стуле": "a boy sitting on a chair",
    "мы сидим перед доской": "rows of seated boys in front of a blackboard",
    "он сидит со мной": "two men sitting side by side on a bench",
    "мальчик слышит урок": "a boy listening attentively, a hand behind his ear",
    "я слышу урок": "a boy listening attentively, a hand behind his ear",
    "ты слышишь учителя": "a boy listening to a teacher, a hand behind his ear",
    "мы слышим учителя": "three boys listening to one adult man at a blackboard",
    "студент понимает урок": "a male student at a desk with a glowing lightbulb overhead",
    "я понимаю урок": "a pupil at a desk with a glowing lightbulb overhead",
    "ты понимаешь урок": "a pupil at a desk with a glowing lightbulb overhead",
    "мы понимаем урок": "three boys at desks with glowing lightbulbs overhead",
    "он понимает язык": "a man with a glowing lightbulb overhead beside an ornate open book",
    "ты понимаешь язык": "a man with a glowing lightbulb overhead beside an ornate open book",
    "студент понимает урок?": "a pupil at a desk, questioning gesture beside him",
    "ты понимаешь урок? (к мужчине)": "two men at a desk, one asking with a questioning gesture",
    "мальчик смотрит телевизор": "a boy watching a television screen",
    "я смотрю телевизор": "a boy watching a television screen",
    "мальчик смотрит на луну": "a boy looking up at the moon in a night sky",
    "студент смотрит на доску": "a male student looking at a blackboard",
    "ты смотришь на доску": "a boy looking at a blackboard",
    "я смотрю на солнце": "a boy shading his eyes, looking up at the bright sun",
    "мы смотрим на луну": "two boys looking up at the moon in a night sky",
    "мужчина идёт в мечеть": "a man walking towards a mosque",
    "студент отправляется в школу": "a male student setting off towards a school",
    "он идёт в мечеть": "a man walking towards a mosque",
    "я иду пешком в школу": "a boy walking on foot towards a school",
    "мы идём пешком в мечеть": "three adult men walking on foot towards a mosque",
    "мы идём в школу": "three boys walking towards a school building",
    "я иду на работу": "a man walking towards an office with a briefcase",
    "ты идёшь на работу": "a man walking towards an office with a briefcase",
    "когда студент идёт в школу?": "a student walking to school, a clock on the wall behind",
    "когда ты идёшь в школу? (к мужчине)": "two men, one setting off to school, a clock behind",
    "служащий возвращается с работы": "an office clerk coming home through a garden gate",
    "я возвращаюсь из школы": "a boy coming home from school through a garden gate",
    "мы возвращаемся с работы": "two adult men coming home through a garden gate",
    "когда отец возвращается с работы?": "one man coming home, a clock on the wall behind",
    "врач живёт в городе": "a doctor in a white coat in front of a city house",
    "он живёт в большом доме": "a man in front of one large house",
    "я живу в городе": "a boy in front of a house among city buildings",
    "ты живёшь в городе": "a boy in front of a house among city buildings",
    "мы живём в близком городе": "four people before a house with city buildings right behind",
    "где живёт врач?": "a doctor before a house, a questioning gesture beside him",
    "где ты живёшь? (к мужчине)": "two men before a house, one asking with a gesture",
    "инженер работает в городе": "an engineer in a helmet at work among city buildings",
    "он работает в городе": "a man working at a desk, city buildings behind the window",
    "я работаю в школе": "a teacher working at a desk inside a school",
    "ты работаешь в школе": "a teacher working at a desk inside a school",
    "мы работаем в городе": "two adult men working at desks, city buildings behind the window",
    "ты много работаешь": "a man working at a desk piled high with papers, tired",
    "где работает инженер?": "an engineer at a building site, questioning gesture beside",
    "где ты работаешь? (к мужчине)": "two men, one at a work desk, questioning gesture",
    "кем ты работаешь?": "two men talking, tools and a work desk behind them",
    "мужчина едет в Египет": "a man with a suitcase before the flag of Egypt",
    "студент едет в Турцию": "a male student with a suitcase before the flag of Turkey",
    "я еду в Египет": "a man with a suitcase before the flag of Egypt",
    "ты едешь в Египет": "a man with a suitcase before the flag of Egypt",
    "он едет в Пакистан": "a man with a suitcase before the flag of Pakistan",
    "мы едем в Турцию": "four people with suitcases before the flag of Turkey",
    "куда едет мужчина?": "a man with a suitcase, a questioning gesture beside him",
    "куда ты едешь? (к мужчине)": "two men, one with a suitcase, questioning gesture",
    "учитель едет в школу на автомобиле": "a male teacher driving a car towards a school",
    "как учитель добирается до школы?": "a teacher beside a car and a school, questioning gesture",
    "как ты добираешься на работу? (к мужчине)": "two men beside a car, questioning gesture",
    "студент любит учителя": "two young men smiling warmly side by side",
    "мальчик любит яблоки": "a boy happily holding a handful of red apples",
    "мы любим учителя": "three young men smiling around one adult man teacher",
    "ты любишь этот город? (к мужчине)": "two men before a city, one asking with a gesture",
    "я с тобой (к мужчине)": "two men standing side by side, shoulder to shoulder",
    "он со мной": "two men standing side by side, shoulder to shoulder",
    "мы с ним": "three men standing together in a group",
    "я со своим братом": "two boys standing side by side",
    "он со своим отцом": "two adult men standing side by side",
    "мы с учителем": "three young men standing with one adult man teacher",
    "ты со своим другом (к мужчине)": "two men standing together as friends",
    "студент в школе": "a male student standing inside a school",
    "я студент в школе": "a male student standing in front of a school",
    "ребёнок в комнате": "a small child standing in a room",
    "мальчики в школе": "three boys standing inside a school",
    "учителя в школе": "three adult men standing inside a school",
    "преподаватели в школе": "three adult men with books standing inside a school",
    "студенты перед доской": "rows of seated young men in front of a blackboard",
    "мусульмане в мечети": "four adult men in white robes gathered inside a mosque",
    "друзья в доме": "four boys together inside a house",
    "инженеры на работе": "three adult male engineers in helmets at a building site",
    "инженер на работе": "an engineer in a helmet at a building site",
    "врач в городе": "a doctor in a white coat among city buildings",
    "полицейский перед дверью": "a police officer standing in front of a door",
    "мы в мечети": "three adult men standing inside a mosque",
    "он в школе": "a boy standing inside a school",
    "я дома": "a boy standing inside his own home",
    "в школе есть врач": "a doctor in a white coat standing inside a school",
    "кто в комнате?": "an open door to a room with one person inside, questioning gesture",
    "сколько студентов в комнате?": "young men standing in a room, questioning gesture beside",
    "сколько мальчиков в семье?": "four boys standing in a row, questioning gesture beside",
    "сколько братьев в твоей семье?": "four boys standing in a row, questioning gesture beside",
    "какое гражданство у этого мужчины?": "a man holding an open passport, questioning gesture",
    "гражданство студента": "a male student holding an open passport",
    "где твой отец?": "a boy looking around for someone, questioning gesture",
    "ты отсюда? (к мужчине)": "two men in a street, one pointing at the ground questioningly",
    "да, я отсюда": "a man nodding yes, pointing down at the ground of his own street",
    "это дом": "one small house seen from outside",
    "это школа": "one school building",
    "это мечеть": "one mosque with a dome and a minaret",
    "это автомобиль": "one car seen from the side",
    "это книга": "one closed book lying on a table",
    "это чемодан": "one travel suitcase with a handle",
    "это ручка": "one ballpoint pen",
    "это газета": "one folded newspaper",
    "это ключ": "one metal door key",
    "это стол": "one wooden table",
    "это стул": "one wooden chair",
    "это холодильник": "one closed white refrigerator",
    "это телефон": "one telephone handset",
    "это корабль": "one ship on the sea",
    "это конь": "one horse standing",
    "это кошка": "one cat sitting",
    "это лев": "one lion sitting",
    "это дерево": "one leafy tree",
    "это дверь": "one closed wooden door",
    "это роза": "one red rose flower",
    "это тетрадь": "one school exercise notebook",
    "это классная доска": "one blank classroom blackboard",
    "это конверт": "one sealed paper envelope",
    "это самолёт": "one airplane flying in the sky",
    "это верблюд": "one camel standing on desert sand",
    "это книга?": "a hand pointing at a book with a questioning gesture",
    "да, это книга": "one book on a table with a green check mark beside it",
    "это школа?": "a hand pointing at a school building, questioning gesture",
    "да, это школа": "a school building with a green check mark beside it",
    "что это? (о муж. роде)": "a hand pointing at an object with a questioning gesture",
    "что это? (о жен. роде)": "a hand pointing at an object with a questioning gesture",
    "что это за книга?": "a hand pointing at a book with a questioning gesture",
    "это правильно": "a big bold green check mark",
    "это ошибка": "a big bold red cross mark",
    "это правильно, а это ошибка": "a green check mark beside a red cross mark",
    "этот дом большой": "one very large house seen from outside",
    "большой дом": "one very large house seen from outside",
    "эта комната маленькая": "one tiny cramped room seen from inside",
    "эта книга новая": "one brand new shiny book",
    "новая книга": "one brand new shiny book",
    "моя книга новая": "one brand new shiny book on a desk",
    "эта газета старая": "one old yellowed crumpled newspaper",
    "старая школа": "one old worn school building",
    "этот язык красивый": "an open book with beautiful decorative ornament on its pages",
    "наш язык красивый": "an open book with beautiful decorative ornament on its pages",
    "этот лев сильный": "one powerful muscular lion roaring",
    "сильный конь": "one powerful muscular horse rearing up",
    "этот осёл слабый": "one thin weary donkey with a drooping head",
    "эта рубашка красивая": "one beautiful brightly patterned shirt",
    "это пальто безобразное": "one ugly shabby stained overcoat",
    "красивая роза": "one beautiful blooming red rose",
    "эта еда хорошая": "one appetising plate of warm delicious food",
    "эта еда плохая": "one spoiled unappetising plate of food",
    "этой воды мало": "just a little water at the bottom of a tall glass",
    "на столе много еды": "a table crowded with many plates of food",
    "слон ест много": "one elephant eating from a huge heap of hay and fruit",
    "этот город далёкий": "one city far away on the horizon",
    "близкий город": "one city standing right nearby beyond a field",
    "эта мечеть близко": "one mosque right across the street",
    "мой автомобиль новый": "one brand new shiny car",
    "твой автомобиль перед домом (к мужчине)": "one car parked in front of a house",
    "его автомобиль старый": "one old rusty worn-out car",
    "её автомобиль красивый": "one beautiful shiny elegant car",
    "её телефон новый": "one brand new telephone",
    "книг много": "a great many books stacked in tall piles",
    "дома новые": "a row of brand new freshly painted houses",
    "города далеко": "several cities far away on the horizon",
    "уроки лёгкие": "open notebooks with neat easy exercises on the pages",
    "чемоданы новые": "several brand new shiny suitcases",
    "кошки маленькие": "several tiny little kittens",
    "верблюдов много": "a great many camels crowded together on sand",
    "мечетей в городе много": "a city skyline with many domes and minarets",
    "есть новый урок": "one brand new open notebook on a desk",
    "дом большой, а комната маленькая": "one large house beside one tiny cramped room",
    "мечеть близко, а школа далеко": "a mosque right nearby and a school far on the horizon",
    "верблюд высокий, а осёл низкий": "one tall camel standing beside one short donkey",
    "лев сильный, а птичка слабая": "one powerful lion beside one tiny frail sparrow",
    "книга новая, а газета старая": "one shiny new book beside one old yellowed newspaper",
    "еды много, а воды мало": "a heap of food beside a glass with only a little water",
    "роза красивая, а забор безобразный": "one blooming rose beside one broken ugly fence",
    "книга здесь": "one book lying close in the foreground",
    "мечеть там": "one mosque far away on the horizon",
    "наша книга там": "one book lying far away on a distant table",
    "её книга здесь": "one book lying close in the foreground",
    "книга здесь, а тетрадь там": "one book close in front and one notebook far away",
    "дверь дома": "the front door of a house",
    "дверь мечети": "the carved door of a mosque",
    "ключ от автомобиля": "one car key on a keyring",
    "молоко коровы": "a cow standing beside a full pail of milk",
    "яйца курицы": "a hen beside a nest of eggs",
    "фотография города": "one printed photograph of a city",
    "город Посланника": "a city of white houses around a great mosque",
    "книга на столе": "a book lying on a wooden table",
    "на столе есть книга": "a book lying on a wooden table",
    "хлеб на столе": "a loaf of bread on a wooden table",
    "птичка на дереве": "a small sparrow perched on a tree branch",
    "книги на парте": "books lying on a school desk",
    "ключи на столе": "keys lying on a wooden table",
    "Коран на парте": "an open quran on a school desk",
    "ручка в чемодане": "a pen inside an open suitcase",
    "ручки в чемодане": "several pens inside an open suitcase",
    "ключ в конверте": "a key inside an open envelope",
    "вода в стакане": "water filling a glass",
    "мясо в тарелке": "cooked meat on a plate",
    "ложка в тарелке": "a spoon resting in a plate",
    "молоко в холодильнике": "a bottle of milk inside an open refrigerator",
    "яйца в холодильнике": "eggs on a shelf inside an open refrigerator",
    "кровать в комнате": "a bed standing in a room",
    "телевизор в комнате": "a television set standing in a room",
    "корабль в воде": "a ship floating on the water",
    "в городе есть мечеть": "a mosque standing among city houses",
    "в холодильнике есть хлеб": "bread on a shelf inside an open refrigerator",
    "в комнате есть кровать": "a bed standing in a room",
    "в доме есть телевизор": "a television set inside a house room",
    "в стакане есть вода?": "a glass of water with a questioning gesture beside it",
    "в холодильнике есть молоко?": "an open refrigerator with milk, questioning gesture",
    "в конверте есть ключ?": "an envelope with a key, a questioning gesture beside",
    "есть ли мечеть поблизости?": "a mosque nearby with a questioning gesture beside it",
    "чемодан под партой": "a suitcase on the floor under a school desk",
    "кошка под стулом": "a cat lying under a wooden chair",
    "газета под книгой": "a newspaper lying underneath a book",
    "обувь под кроватью": "a pair of shoes on the floor under a bed",
    "его книга под партой": "a book on the floor under a school desk",
    "твой чемодан под партой (к женщине)": "a suitcase on the floor under a school desk",
    "кошка спит под кроватью": "a cat sleeping on the floor under a bed",
    "солнце над домами": "the sun shining above a row of houses",
    "луна над городом": "the moon shining above a city skyline at night",
    "самолёт над городом": "an airplane flying above a city skyline",
    "голубь над забором": "a pigeon flying above a wooden fence",
    "дерево перед мечетью": "a tree standing in front of a mosque",
    "автомобили перед домом": "cars parked in front of a house",
    "деревья перед домом": "trees standing in front of a house",
    "конь за домом": "a horse standing behind a house",
    "за домом есть конь": "a horse standing behind a house",
    "за школой есть забор": "a wooden fence standing behind a school building",
    "парта справа от двери": "a school desk standing to the right of a door",
    "стул слева от стола": "a chair standing to the left of a table",
    "твоя книга на столе (к мужчине)": "a book lying on a wooden table",
    "твоя книга в чемодане (к женщине)": "a book inside an open suitcase",
    "его ручка в чемодане": "a pen inside an open suitcase",
    "наш ключ в конверте": "a key inside an open envelope",
    "что в чемодане?": "an open suitcase with a questioning gesture above it",
    "сколько книг на парте?": "books on a school desk with a questioning gesture beside",
    "дом моего дедушки старый": "one old weathered house seen from outside",
    # --- Третий диалог ---------------------------------------------------------
    "это призыв на молитву": "one man on the balcony of a minaret, hands cupped at his mouth",
    "пойдём скорее в мечеть": "two men hurrying towards a mosque, one beckoning the other",
    # Пропажу видно по пустому месту: вешалка без пальто, футляр без очков.
    "где пальто?": "one empty coat hanger with a questioning gesture beside it",
    "вот пальто": "a hand holding out one long winter overcoat",
    "где очки?": "one open empty eyeglass case with a questioning gesture beside it",
    "вот очки": "a hand holding out one pair of eyeglasses",
    "мальчик в ванной": "a boy washing his hands at a washbasin in a bathroom",
    "эта мечеть большая": "one very large mosque with a wide dome and tall minarets",
}
