"""Промпты для отдельных слов колоды.

Деление на «с людьми» и «без людей» — не порядок ради порядка: к первым
приписывается правило скромности, и приписывать его ко всему подряд нельзя,
«волос не видно» рядом с кошкой даёт лысую кошку.

Чего здесь нет намеренно:
  * числительных — модель ошибается в счёте, а неверное число учит вранью;
  * служебных слов и вопросов — «из», «для», «почему» не изображаются;
  * относительных признаков без пары и абстракций — «уровень», «гражданство»;
  * всего, что требует надписи, — «имя», «первый»: в стиле стоит `no text`.
"""

#: Женская фигура задумана: только сюда приписывается MODESTY.
WITH_WOMEN: dict[str, str] = {
    "девочка": "one cheerful girl wearing a hijab, modest dress, full figure",
    "девочки": "three cheerful girls wearing hijabs and modest dresses",
    "женщина": "one adult woman wearing a hijab and modest long dress, full figure",
    "женщины": "three adult women wearing hijabs and modest long dresses",
    "подруга": "two girls standing side by side",
    "подруги": "four girls standing together in a group",
    "учительница": "a female teacher wearing a hijab at a blackboard holding chalk",
    "учительницы": "three female teachers wearing hijabs in a classroom",
    "студентка": "a female student wearing a hijab with a backpack and notebook",
    "студентки": "three female students wearing hijabs with backpacks",
    "врач (жен. род)": "a female doctor wearing a hijab and white coat with a stethoscope",
    "врачи (жен. род)": "three female doctors wearing hijabs and white coats",
    "мусульманка": "a muslim woman in a hijab and modest long dress",
    "мусульманки": "a group of muslim women in hijabs and modest long dresses",
    "семья": "one adult man, one adult woman, one boy and one girl standing together",
    "мать": "one adult woman holding one small child on her arm",
    "матери": "three adult women each holding one small child",
    "сестра": "two girls standing side by side",
    "сёстры": "three girls standing in a row",
    "бабушка": "one elderly woman with a kind wrinkled face",
    "бабушки": "three elderly women standing in a row",
    "дочь": "one adult woman and one girl standing side by side",
    "дочери": "one adult woman and three girls standing in a row",
    "тётя (со стороны отца)": "one adult woman and one girl standing side by side",
    "тёти (со стороны отца)": "three adult women standing in a row",
    "тётя (со стороны матери)": "one adult woman and one girl standing side by side",
    "готовит (о еде)": "a woman wearing a hijab cooking at a stove",
    "женатый": "a groom and a bride in a hijab standing together",
    "египтянка": "an Egyptian woman standing beside the flag of Egypt",
    "египтянки": "a group of Egyptian women beside the flag of Egypt",
    "сирийка": "a Syrian woman standing beside the flag of Syria",
    "любит": "one boy hugging one adult woman warmly",
    "тёти (со стороны матери)": "three adult women standing in a row",
    "дети": "three small children playing together: two boys and one girl",
}

#: Предметы, животные и картинки, где люди только мужского пола.
REST: dict[str, str] = {
    "мальчик": "one cheerful boy standing, full figure",
    "мальчики": "three cheerful boys standing together",
    "мужчина": "one adult man standing, full figure",
    "мужчины": "three adult men standing together",
    "ребёнок": "one small boy toddler standing",
    "друг": "two boys standing side by side",
    "друзья": "four boys standing together in a group",
    "учитель": "a male teacher at a blackboard holding chalk",
    "учителя (муж. род)": "three male teachers standing in a classroom",
    "преподаватель": "a male university lecturer with books at a lectern",
    "преподаватели": "three male university lecturers with books",
    "студент": "a male student with a backpack and notebook",
    "студенты": "three male students with backpacks and notebooks",
    "врач (муж. род)": "a male doctor in a white coat with a stethoscope",
    "врачи (муж. род)": "three male doctors in white coats with stethoscopes",
    "инженер": "one adult male engineer in a helmet holding blueprints",
    "инженеры": "three adult male engineers in helmets holding blueprints",
    "полицейский": "one adult male police officer in uniform and cap",
    "полицейские": "three adult male police officers in uniform",
    "должностное лицо": "one adult male office clerk at a desk with papers and a stamp",
    "должностные лица": "three adult male office clerks at desks with papers",
    "мусульманин": "a muslim man in a white robe and prayer cap",
    "мусульмане": "a group of muslim men in white robes and prayer caps",
    "отец": "one adult man holding one small boy on his arm",
    "отцы": "three adult men each holding one small boy",
    "брат": "two boys standing side by side",
    "братья": "three boys standing in a row",
    "дедушка": "one elderly man with a grey beard leaning on a cane",
    "дедушки": "three elderly men with grey beards standing in a row",
    "сын": "one adult man and one boy standing side by side",
    "сыновья": "one adult man and three boys standing in a row",
    "дядя (со стороны отца)": "one adult man and one boy standing side by side",
    "дяди (со стороны отца)": "three adult men standing in a row",
    "дядя (со стороны матери)": "one adult man and one boy standing side by side",
    "кушает": "a boy eating a meal at a table",
    "читает": "a boy reading an open book",
    "пьёт": "a boy drinking water from a glass",
    "пишет": "a boy writing in a notebook with a pen",
    "молится": "a muslim man praying on a prayer rug",
    "бежит": "a boy running fast",
    "совершает малое омовение": "a man washing his hands and arms at a tap for ablution",
    "сидит": "a boy sitting on a chair",
    "открывает": "a hand opening a wooden door",
    "закрывает": "a hand closing a wooden door",
    "смеётся": "a boy laughing happily",
    "играет": "a boy playing with a ball",
    "ходит, идёт": "a boy walking along a path",
    "нюхает": "a boy smelling a flower",
    "спит": "a boy sleeping in a bed",
    "садится верхом, едет (на чём-либо)": "a boy riding on a horse",
    "работает": "a man working at a desk",
    "отправляется в путешествие": "a traveller with a suitcase at an airport",
    "счастливый": "a boy with a wide happy smile",
    "печальный": "a boy with a sad downcast face",
    "больной": "a boy lying sick in bed with a thermometer",
    "холостой": "one lone young man standing by himself",
    "активный": "a boy energetically running and jumping, bright lively face",
    "ленивый": "a boy sprawled lazily on a sofa, yawning",
    "здоровый": "a cheerful boy with rosy cheeks running easily",
    "лёгкий": "a boy lifting a huge balloon with one finger, no effort",
    "тяжёлый": "a boy straining to lift a heavy stone block",
    "сильный": "a strong man easily lifting a heavy barbell overhead",
    "там": "a boy pointing far away towards the horizon",
    "здесь": "a boy pointing down at the ground right at his feet",
    "большой": "a giant oversized ball towering over a small child beside it",
    "египтянин": "an Egyptian man standing beside the flag of Egypt",
    "египтяне": "a group of Egyptian men beside the flag of Egypt",
    "пакистанец": "a Pakistani man standing beside the flag of Pakistan",
    "турок": "a Turkish man standing beside the flag of Turkey",
    "выходит": "a boy stepping out through an open door, leaving the house",
    "заходит": "a boy stepping in through an open doorway, entering a room",
    "слышит": "a boy cupping a hand behind his ear, listening closely",
    "наблюдает, просматривает": "a boy watching a television screen attentively",
    "отправляется": "a boy setting off down a road, walking away from the viewer",
    "возвращается": "a boy coming back home through the garden gate",
    "понимает": "a boy at a desk with a glowing lightbulb above his head",
    "проживает": "a boy standing in front of his own house",
    "смотрит": "a boy looking upwards with wide attentive eyes",
    "урок": "a lesson in progress: pupils at desks, a teacher at the blackboard",
    "уроки": "several classrooms with lessons going on",
    "работа": "a man working at a desk in an office",
    "работы": "several men working at desks in an office",
    "речь": "a man speaking, an empty blank speech bubble beside his mouth",
    "приветствие (ед. ч.)": "two men greeting each other with a handshake and smiles",
    "приветствия (мн. ч.)": "several pairs of people greeting each other warmly",
    "знакомство": "two men meeting for the first time, shaking hands",
    "знакомства": "a group of people meeting and shaking hands",
    "да": "a boy nodding his head yes with a happy face",
    "учителя": "three male teachers standing in a classroom",
    "семьи": "three separate groups of people standing apart from one another",
    "дяди (со стороны матери)": "three adult men standing in a row",
    "верблюд": "one camel standing on desert sand",
    "верблюды": "a herd of camels on desert sand",
    "конь": "one horse standing in a meadow",
    "кони": "a herd of horses in a meadow",
    "осёл": "one grey donkey standing",
    "ослы": "several grey donkeys standing together",
    "корова": "one cow standing in a green field",
    "коровы": "a herd of cows in a green field",
    "слон": "one grey elephant standing",
    "слоны": "a herd of grey elephants",
    "лев": "one lion with a mane sitting",
    "львы": "a pride of lions together",
    "газель": "one gazelle with slender horns standing",
    "газели": "a herd of gazelles",
    "кошка": "one cat sitting",
    "кошки": "several cats sitting together",
    "курица": "one brown hen standing",
    "куры": "several brown hens pecking the ground",
    "петух": "one rooster with a red comb crowing",
    "петухи": "several roosters with red combs",
    "голубь": "one grey pigeon perched",
    "голуби": "a flock of grey pigeons",
    "рыба": "one fish swimming underwater",
    "маленькая птичка": "one tiny sparrow perched on a twig",
    "маленькие птички": "several tiny sparrows on a branch",
    "хлеб": "a loaf of bread on a wooden board",
    "мясо": "raw red meat on a wooden board",
    "молоко": "a tall glass of milk",
    "вода": "a clear glass of water",
    "яйцо": "one white chicken egg",
    "яйца": "several white chicken eggs in a bowl",
    "яблоко": "one red apple",
    "яблоки": "a pile of red apples",
    "апельсин": "one orange fruit",
    "апельсины": "a pile of orange fruits",
    "еда": "a plate of warm food on a table",
    "дом": "one small house with a door and windows, seen from outside",
    "дома": "a row of small houses along a street",
    "комната": "a tidy room with a bed and a window, seen from inside",
    "дверь": "one closed wooden door in a wall",
    "двери": "several wooden doors in a row",
    "стол": "one wooden table, nothing on it",
    "столы": "several wooden tables in a row",
    "стул": "one wooden chair",
    "стулья": "several wooden chairs in a row",
    "кровать": "one neatly made bed in a bedroom",
    "кровати": "several beds in a row in a room",
    "холодильник": "one closed white refrigerator in a kitchen",
    "холодильники": "several white refrigerators in a row",
    "тарелка": "one empty ceramic plate",
    "тарелки": "a stack of ceramic plates",
    "стакан": "one empty drinking glass",
    "стаканы": "several drinking glasses in a row",
    "ложка": "one metal spoon",
    "ложки": "several metal spoons together",
    "телевизор": "one television set on a stand",
    "телевизоры": "several television sets in a row",
    "телефон": "one telephone handset",
    "телефоны": "several telephones in a row",
    "ключ": "one metal door key",
    "ключи": "a bunch of metal door keys",
    "конверт": "one sealed paper envelope",
    "конверты": "several paper envelopes stacked",
    "забор": "a wooden fence along a garden",
    "заборы": "several wooden fences",
    "обувь": "one pair of shoes side by side",
    "рубашка": "one folded shirt",
    "рубашки": "several folded shirts stacked",
    "пальто": "one long winter overcoat on a hanger",
    "одежда": "clothes hanging on a rack",
    "меч": "one straight sword with a hilt",
    "мяч": "one round ball",
    "фотография": "one printed photograph with a white border",
    "книга": "one open book with blank pages",
    "книги": "a stack of closed books",
    "тетрадь": "one school exercise notebook",
    "тетради": "a stack of school exercise notebooks",
    "ручка": "one ballpoint pen",
    "ручки": "several ballpoint pens together",
    "парта": "one school desk with a chair",
    "парты": "rows of school desks in a classroom",
    "классная доска": "one green classroom blackboard, blank",
    "классные доски": "several classroom blackboards, blank",
    "школа": "one school building with a yard, seen from outside",
    "школы": "several school buildings",
    "газета": "one folded newspaper",
    "газеты": "a stack of folded newspapers",
    "рукописный экземпляр Корана": "an open handwritten quran on a wooden book stand",
    "рукописные экземпляры Корана": "several handwritten qurans stacked on a shelf",
    "мечеть": "one mosque with a dome and a minaret, seen from outside",
    "мечети": "several mosques with domes and minarets",
    "город": "a city of houses and towers seen from a distance",
    "дерево": "one leafy tree",
    "деревья": "a group of leafy trees",
    "роза": "one red rose flower",
    "розы": "a bouquet of red roses",
    "солнце": "the bright sun in a clear blue sky",
    "луна": "the moon in a dark night sky with stars",
    "чемодан": "one closed travel suitcase with a handle",
    "чемоданы": "several travel suitcases together",
    "автомобиль": "one car seen from the side",
    "автомобили": "several cars parked in a row",
    "корабль": "one ship sailing on the sea",
    "корабли": "several ships sailing on the sea",
    "самолёт": "one airplane flying in the sky",
    "самолёты": "several airplanes flying in the sky",
    "Пакистан": "the flag of Pakistan on a flagpole",
    "Турция": "the flag of Turkey on a flagpole",
    "Египет": "the flag of Egypt on a flagpole",
    "Сирия": "the flag of Syria on a flagpole",
    "на": "a red ball lying on top of a wooden table",
    "в (внутри)": "a red ball inside an open wooden box",
    "под": "a red ball on the floor underneath a wooden table",
    "над": "a red ball floating in the air above a wooden table",
    "перед": "a red ball on the floor in front of a wooden chair",
    "за": "a red ball on the floor behind a wooden chair",
    "справа от": "a red ball on the floor to the right of a wooden chair",
    "слева от": "a red ball on the floor to the left of a wooden chair",
    "маленький": "one tiny red ball resting in an open palm",
    "много": "a big heaped pile of many red apples",
    "мало": "just two red apples alone on a large empty plate",
    "высокий, длинный": "a very tall giraffe standing beside a low bush",
    "низкий, короткий": "a very short dachshund standing beside a tall pole",
    "худой": "one very thin lanky cat standing",
    "толстый": "one very plump round cat sitting",
    "близкий": "two small houses standing right next to each other",
    "далёкий": "one small house far away on the horizon across an empty field",
    "хороший": "a hand giving a clear thumbs up",
    "плохой": "a hand giving a clear thumbs down",
    "слабый": "a tiny tired kitten barely standing on wobbly legs",
    "ошибка": "a big bold red cross mark",
    "правильный": "a big bold green check mark",
    "безобразный": "an ugly crooked broken-down old fence",
    "красивый": "a beautiful blooming flower garden",
    "новый": "a brand new shiny bicycle",
    "старый": "an old rusty worn-out bicycle",
    "это (муж. род)": "a hand pointing at a single object on a table",
    "это (жен. род)": "a hand pointing at a single object on a table",
    "Это (муж. род)": "a hand pointing at a single object on a table",
    "Это (жен. род)": "a hand pointing at a single object on a table",
    "рыбы": "a school of fish swimming underwater",
    "комнаты": "several tidy rooms seen from inside",
    "солнца": "the bright sun in a clear blue sky",
    "луны": "the phases of the moon across a night sky",
    "воды": "clear water filling a glass",
    "мяса": "several cuts of raw red meat on a wooden board",
    "молока": "several glass bottles of milk",
    "еды": "several plates of warm food on a table",
    "одежды": "clothes hanging in a row on a rack",
    "обуви": "several pairs of shoes standing in a row",
    "мячи": "several round balls together",
    "мечи": "several straight swords laid out",
    "города": "several cities seen from a distance",
    "пальто (мн. ч.)": "several long winter overcoats on a rack",
    "фотографии": "several printed photographs scattered on a table",
    "раздел, глава": "an open book with a ribbon bookmark between chapters",
    "разделы, главы": "several open books with ribbon bookmarks",
}
